# Run from project root:
# docker-compose -p leia -f docker/docker-compose.yml up

version: '3.3'

services:
  mongod:
    image: mongo:3.6
    container_name: mongo
    ports:
      - 27017:27017
    networks:
      - leia
    command:
      - "mongod"
    volumes:
      - mongodbdata:/data/db

  schemata:
    image: leia/schemata:latest
    container_name: schemata
    ports:
      - 5005:5005
    networks:
      - leia
    command:
      - "python"
      - "-m"
      - "schema.service"
      - "host=0.0.0.0"
    environment:
      - ARCHIVE_PATH=/app/archives
      - REPO_ACTIVE=canonical-v.1.0.0
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - AWS_ACCESS_KEY_ID=???
      - AWS_SECRET_ACCESS_KEY=???
      - EDITING_ENABLED=True
    volumes:
      - repository-archives:/app/archives
    depends_on:
      - mongod

volumes:
  repository-archives:
  mongodbdata:

networks:
  leia:
    driver: bridge